########################################################
#@@@-------------GENERATED BY AUTO_MAKE-------------@@@#
#@@                                                  @@#
#@  https://github.com/kagestonedragon/auto_make_php  @#
########################################################

NAME = jopa

GCC = gcc

GCC_FLAGS = -Wall -Wextra -Werror

OBJ_PATH = objects/

INCLUDE_HEADERS = headers/
INCLUDE_HH = hh/

TEST_PATH = test/
TEST_INNER_PATH = test/inner/
TEST_FILES = \
			123.c\
			test.c
TEST_INNER_FILES = \
			test.c

OBJ_TEST_CORE = $(addprefix $(OBJ_PATH), $(TEST_FILES:.c=.o))
OBJ_TEST_INNER_CORE = $(addprefix $(OBJ_PATH), $(TEST_INNER_FILES:.c=.o))

OBJECTS = $(TEST) $(TEST_INNER) 

all: $(NAME)
		make -C dep/test1
		make -C dep/test2

$(NAME): $(OBJECTS)
		@($(GCC) $(GCC_FLAGS) -o $(NAME) $(OBJECTS) -L dep/ft_printf -lftprintf -L dep/libft -lft)
		@(echo "^[[0;92m"$(NAME) "was created!^[[0;0m")
clean:
		make clean -C dep/test1
		make clean -C dep/test2
		@(/bin/rm -rf $(OBJ_PATH))
		@(echo "^[[0;91mAll object files have been deleted!^[[0;0m")

fclean:
		make fclean -C dep/test1
		make fclean -C dep/test2
		@(/bin/rm -f $(NAME))
		@(echo "^[[0;91m"$(NAME) "has been deleted!^[[0;0m")

re:
		make fclean -C dep/test1
		make fclean -C dep/test2
		make -C dep/test1
		make -C dep/test2
		fclean
		all

objects:
		@(mkdir $(OBJ_PATH))

objects/%.o: $(TEST)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_HEADERS) $(INCLUDE_HH) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

objects/%.o: $(TEST_INNER)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDE_HEADERS) $(INCLUDE_HH) -c $< -o $@)
		(echo "^[[0;93m"$< "->" $@"^[[0;0m")

